# Generated by Django 3.0.7 on 2020-07-14 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200711_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(choices=[('S', 'Shirt'), ('SW', 'Sports Wear'), ('OW', 'Outwear')], max_length=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Category'),
        ),
    ]
